### ISSUE TITLE
Test 분리

### ISSUE THREAD

**Issue by devholic** [honeyqa/worker-java#1]
Worker 소스를 살펴보다 보니 Test와 Source가 나누어져있지 않아서 Test를 분리하려고 합니다.

일단 제가 작업한 Proguard 부분은 나눠서 진행했는데, 나머지 @JungMinu 형이 작성하신 나머지 코드도 Test와 Source를 나누면 어떨까 싶어 이슈 생성합니다.

**Comment by JungMinu** [comment]
@devholic 분리작업끝ㅋ
